services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper_rss
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_rss
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1

      # Kafka nói chuyện với Zookeeper trong docker network
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Lắng nghe mọi nơi trong container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      # Quảng cáo cho app chạy TRÊN MÁY HOST
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
